name: flutter_google_places_sdk
description: A Flutter plugin for google places sdk that uses the native libraries on each platform
version: 0.3.7
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_sdk_platform_interface: ^0.2.7
  flutter_google_places_sdk_ios: ^0.1.3
  flutter_google_places_sdk_android: ^0.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_google_places_sdk_android
      ios:
        default_package: flutter_google_places_sdk_ios
